plugins {
    id 'java'
    alias libs.plugins.shadowJar
    id 'maven-publish'
}

group = 'org.brain4j'
version = '3.0.0-SNAPSHOT'

def brain4jJavaTargetVersion = providers.gradleProperty("brain4j.javaTargetVersion")
        .map(Integer::parseInt)
        .orElse(22)
def currentJavaLanguageVersion = JavaVersion.current().majorVersion as Integer
def brain4jJavaToolchainVersion = Math.max(brain4jJavaTargetVersion.get(), currentJavaLanguageVersion)
def brain4jJavaVersion = JavaVersion.toVersion(brain4jJavaTargetVersion.get())

subprojects {
    version = rootProject.version
    group = rootProject.group

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
        maven {
            name "brain4jReleases"
            url "https://repo.brain4j.org/releases"
        }
        maven {
            name "brain4jSnapshots"
            url "https://repo.brain4j.org/snapshots"
        }
    }

    publishing {
        repositories {
            maven {
                name = "brain4j"

                def releasesRepo = uri("https://repo.brain4j.org/releases")
                def snapshotsRepo = uri("https://repo.brain4j.org/snapshots")

                url = version.endsWith("SNAPSHOT") ? snapshotsRepo : releasesRepo

                credentials {
                    username = findProperty("BRAIN4J_USERNAME")
                    password = findProperty("BRAIN4J_TOKEN")
                }

                authentication {
                    basic(BasicAuthentication)
                }
            }
        }
        publications {
            gpr(MavenPublication) {
                from components.java
                groupId = project.group
                artifactId = project.name
                version = project.version
            }
        }
    }

    compileJava {
        options.encoding = "UTF-8"
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(brain4jJavaToolchainVersion))
        }

        sourceCompatibility = brain4jJavaVersion
        targetCompatibility = brain4jJavaVersion
    }
}

tasks.register('buildAll') {
    dependsOn ':brain4j-datasets:shadowJar',
              ':brain4j-math:shadowJar',
              ':brain4j-core:shadowJar',
              ':brain4j-llm:shadowJar'

    doLast {
        println 'Completed build for all modules.'
    }
}

tasks.register('publishAll') {
    dependsOn ':brain4j-datasets:publish',
              ':brain4j-math:publish',
              ':brain4j-core:publish',
              ':brain4j-llm:publish'

    doLast {
        println 'Published all modules to the main repository.'
    }
}
