plugins {
    id 'java'
    alias libs.plugins.shadowJar
    id 'maven-publish'
}

group = 'org.brain4j'
version = '3.0.0-SNAPSHOT'

def javaVersion = 22

subprojects {
    version = rootProject.version
    group = rootProject.group

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    repositories {
        mavenCentral()
        maven {
            name "brain4jReleases"
            url "https://repo.brain4j.org/releases"
        }
        maven {
            name "brain4jSnapshots"
            url "https://repo.brain4j.org/snapshots"
        }
    }

    publishing {
        repositories {
            maven {
                name = "brain4j"

                def releasesRepo = uri("https://repo.brain4j.org/releases")
                def snapshotsRepo = uri("https://repo.brain4j.org/snapshots")

                url = version.endsWith("SNAPSHOT") ? snapshotsRepo : releasesRepo

                credentials {
                    username = findProperty("brain4jUser") ?: System.getenv("brain4jUser")
                    password = findProperty("brain4jPass") ?: System.getenv("brain4jPass")
                }

                authentication {
                    create("basic", BasicAuthentication)
                }
            }
        }
        publications {
            create("gpr", MavenPublication) {
                from components.java
                groupId = project.group
                artifactId = project.name
                version = project.version
            }
        }
    }

    compileJava {
        options.encoding = "UTF-8"
        options.compilerArgs.addAll(["--enable-preview"])
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(javaVersion)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = javaVersion
        options.compilerArgs.addAll(["--enable-preview"])
    }

    tasks.withType(Test).configureEach {
        jvmArgs("--enable-preview", "--add-modules", "jdk.incubator.vector")
    }

    tasks.withType(JavaExec).configureEach {
        jvmArgs("--enable-preview", "--add-modules", "jdk.incubator.vector")
    }
}

tasks.register('buildAll') {
    dependsOn ':brain4j-datasets:shadowJar',
            ':brain4j-math:shadowJar',
            ':brain4j-core:shadowJar',
            ':brain4j-dashboard:shadowJar'

    doLast {
        println 'Completed build for all modules.'
    }
}

tasks.register('publishAll') {
    dependsOn ':brain4j-datasets:publish',
            ':brain4j-math:publish',
            ':brain4j-core:publish',
            ':brain4j-dashboard:publish'

    doLast {
        println 'Published all modules to the main repository.'
    }
}
