plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly(libs.junitPlatform)
    testImplementation(platform(libs.junitBom))
    testImplementation(libs.junitJupiter)

    implementation(project(":brain4j-core"))
    implementation(project(":brain4j-math"))
    implementation(project(":brain4j-llm"))
    implementation(project(":brain4j-datasets"))

    implementation libs.siliconCuda
    implementation libs.siliconMetal
    implementation libs.siliconOpenCL
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(22))
    }

    sourceCompatibility = JavaVersion.VERSION_22
    targetCompatibility = JavaVersion.VERSION_22
}

test {
    useJUnitPlatform()
}