plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testRuntimeOnly(libs.junitPlatform)
    testImplementation(platform(libs.junitBom))
    testImplementation(libs.junitJupiter)
    testImplementation("org.bytedeco:javacv-platform:1.5.12")

    implementation(project(":brain4j-core"))
    implementation(project(":brain4j-math"))
    implementation(project(":brain4j-llm"))
    implementation(project(":brain4j-datasets"))

    implementation(libs.siliconCuda) {
        changing = true
    }
    implementation(libs.siliconMetal) {
        changing = true
    }
    implementation(libs.siliconOpenCL) {
        changing = true
    }

}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(22))
    }

    sourceCompatibility = JavaVersion.VERSION_22
    targetCompatibility = JavaVersion.VERSION_22
}

test {
    useJUnitPlatform()
}