plugins {
    id "java"
    alias libs.plugins.shadowJar
    alias libs.plugins.protobuf
}

configurations.configureEach {
    resolutionStrategy {
        cacheChangingModulesFor 0, 'seconds'
        cacheDynamicVersionsFor 0, 'seconds'
    }
}

dependencies {
    implementation project(":brain4j-math")

    implementation libs.gson
    implementation libs.protobufJava

    testImplementation libs.guava
    testImplementation libs.commonsCsv

    testRuntimeOnly libs.junitPlatform
    testImplementation libs.junitJupiter
    testImplementation platform(libs.junitBom)
    testImplementation project(":brain4j-datasets")
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveFileName = "brain4j-core-${parent.version}.jar"
    exclude "org/brain4j/math/**"
}

tasks.withType(JavaExec).configureEach {
    jvmArgs(["--add-modules", "jdk.incubator.vector", "-XX:+UseSerialGC"])
}
