plugins {
    id "java"
    alias libs.plugins.shadowJar
}

dependencies {
    implementation project(':silicon-api')

    runtimeOnly project(':silicon-opencl')
    // runtimeOnly project(':silicon-cuda')
    // runtimeOnly project(':silicon-metal')

    implementation platform(libs.lwjglBom)
    implementation libs.lwjgl
    implementation libs.lwjglOpenCL

    implementation libs.gson

    testRuntimeOnly(libs.junitPlatform)
    testImplementation(platform(libs.junitBom))
    testImplementation(libs.junitJupiter)
    testRuntimeOnly project(':silicon-opencl')
}

compileJava {
    options.compilerArgs.addAll(["--add-modules", "jdk.incubator.vector"])
}

compileTestJava {
    options.compilerArgs.addAll(["--add-modules", "jdk.incubator.vector"])
}

test {
    useJUnitPlatform()
    jvmArgs '--add-modules', 'jdk.incubator.vector'
}

shadowJar {
    minimize()
    archiveFileName = "brain4j-math-${parent.version}.jar"
}