plugins {
    id "java"
    alias libs.plugins.shadowJar
}

dependencies {
    implementation libs.jacksonDatabind

    implementation(libs.siliconApi) {
        changing = true
    }
    runtimeOnly(libs.siliconCuda) {
        changing = true
    }
    runtimeOnly(libs.siliconMetal) {
        changing = true
    }

    testRuntimeOnly libs.junitPlatform
    testImplementation platform(libs.junitBom)
    testImplementation libs.junitJupiter
}

compileJava {
    options.compilerArgs.addAll(["--add-modules", "jdk.incubator.vector"])
}

test {
    useJUnitPlatform()
    jvmArgs '--add-modules', 'jdk.incubator.vector'
}

shadowJar {
    minimize()
    archiveFileName = "brain4j-math-${parent.version}.jar"
}
