plugins {
    id "java"
    alias libs.plugins.shadowJar
}

dependencies {
    implementation project(":brain4j-core")
    implementation project(":brain4j-math")
    implementation libs.httpclient5
    implementation libs.jacksonDatabind

    implementation libs.slf4jApi
    implementation libs.logbackClassic
}

shadowJar {
    minimize()
    archiveFileName = "brain4j-transformers-${parent.version}.jar"
}

tasks.named("compileJava") {
    dependsOn(":brain4j-core:shadowJar")
}

test {
    failOnNoDiscoveredTests = false
}

tasks.register("cleanModelsCache") {
    description = "Cleans the local Brain4J models cache"
    group = "development"
    doLast {
        def cacheDir = new File(System.getProperty("user.home"), ".cache/brain4j/models")
        if (cacheDir.exists()) {
            delete cacheDir
            println "Cleaned cache directory: ${cacheDir.absolutePath}"
        } else {
            println "Cache directory does not exist: ${cacheDir.absolutePath}"
        }
    }
}
