name: Build

on:
  push:
    branches:
      - "3.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (ShadowJar)
        run: ./gradlew buildAll

      - name: Archive build core artifact
        uses: actions/upload-artifact@v4
        with:
          name: brain4j-core-artifact
          path: brain4j-core/build/libs/*.jar
      
      - name: Archive build math artifact
        uses: actions/upload-artifact@v4
        with:
          name: brain4j-math-artifact
          path: brain4j-math/build/libs/*.jar
      
      - name: Archive build datasets artifact
        uses: actions/upload-artifact@v4
        with:
          name: brain4j-datasets-artifact
          path: brain4j-datasets/build/libs/*.jar
